### ISSUE TITLE
sh make.sh error

### ISSUE THREAD

**Issue by binyi10** [soeaver/Parsing-R-CNN#17]
after sh make.sh, I got error
“
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/meituan/cephfs/user/hadoop-hotelmining/binyi/ParsingRCNN/P-RCNN/Parsing-R-CNN/models/ops/__init__.py", line 3, in <module>
    from .nms import nms, ml_nms
  File "/opt/meituan/cephfs/user/hadoop-hotelmining/binyi/ParsingRCNN/P-RCNN/Parsing-R-CNN/models/ops/nms.py", line 1, in <module>
    from models.ops import _C
ImportError: /opt/meituan/cephfs/user/hadoop-hotelmining/binyi/ParsingRCNN/P-RCNN/Parsing-R-CNN/models/ops/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
”
what should I do

**Comment by binyi10** [comment]
I run it in my conda virtualenv
